### ISSUE TITLE
single-bin in udf can't get bin data

### ISSUE THREAD

**Issue by exherb** [aerospike/aerospike-server#20]
# bugs
__________

**OS:** *Docker Image*

**Aerospike version:** *5.2.0.6"*

**Client version:** *Python 4.0.0"

__________

- namespace-config

```bash
single-bin: true
data-in-index: true
```

- define udf

```lua
function get(rec)
  local m = map()
  names = record.bin_names(rec)
  for i, name in ipairs(names) do
    m[name] = rec[name]
  end
  return m
end

function getval(rec)
  return rec['']
end
```

- invoke udf

```python
as_client.put(key, {"": 1})
as_client.apply(key, "xapi", "get", [])
as_client.apply(key, "xapi", "getval", [])
```

return 

```json
{}
''
```

**Comment by exherb** [comment]
may I ask, what is the eta to fix this?
as a enterprise user, This feature is very critical to do some bits operation without overwriting it.

**Comment by bwhisler** [comment]
Thanks for identifying this...
Your "getval" method (using rec['']) is the proper way to get bin data in a single-bin namespace, but it's broken as of server 5.1.  We are planning to release a fix for this later this month.
[Note that the record.bin_names() function returns nil for a single-bin namespace, which is why the "get" method doesn't work.  We don't plan to change that though.  Using rec[''] should be all you need.]

**Comment by bwhisler** [comment]
Update: we have now released a fix for this issue.

**Comment by exherb** [comment]
thanks, I will try latter

**Comment by exherb** [comment]
> Update: we have now released a fix for this issue.

still not working in 5.3.0.3

```
local bitlib = require('bit')

function put_or(rec, binname, bit)
  if aerospike:exists(rec) then
    rec[binname] = bitlib.bor(rec[binname], bit)
    aerospike:update(rec)
  else
    rec[binname] = bit
    aerospike:create(rec)
  end
  return rec[binname]
end
```

another problem is apply this throw Exception when record is not exist: AEROSPIKE_ERR_RECORD_NOT_FOUND

**Comment by kportertx** [comment]
FYI, this UDF could be replaced by a call to [`bit_or`](https://www.aerospike.com/apidocs/python/aerospike_helpers.operations.html#aerospike_helpers.operations.bitwise_operations.bit_or) if the bin contents are bytes/blob.

**Comment by exherb** [comment]
> FYI, this UDF could be replaced by a call to [`bit_or`](https://www.aerospike.com/apidocs/python/aerospike_helpers.operations.html#aerospike_helpers.operations.bitwise_operations.bit_or) if the bin contents are bytes/blob.

impossible for data-in-index: true

**Comment by gooding470** [comment]
The original problem was hot-fixed in 5.1.0.19+, 5.2.0.11+, and 5.3.0.2+.  If you are on 5.3.0.3 and it still doesn't work, it must be a different problem.  We will take a look.  One thing that could be wrong is that for a single-bin namespace, we must always use the empty string as bin name in UDFs.  Are you trying to use a bin name that's not the empty string?

**Comment by exherb** [comment]
> The original problem was hot-fixed in 5.1.0.19+, 5.2.0.11+, and 5.3.0.2+. If you are on 5.3.0.3 and it still doesn't work, it must be a different problem. We will take a look. One thing that could be wrong is that for a single-bin namespace, we must always use the empty string as bin name in UDFs. Are you trying to use a bin name that's not the empty string?

no, some code.

- define udf

```lua
function getval(rec)
  return rec['']
end
```

- invoke udf

```python
as_client.put(key, {"": 1})
as_client.apply(key, "xapi", "getval", []) -> None
```

I will test again.

**Comment by exherb** [comment]
`Dec 31 2020 07:56:31 GMT: WARNING (udf): (udf_record.c:694) empty bin name`

<img width="776" alt="CleanShot 2020-12-31 at 15 57 10@2x" src="https://user-images.githubusercontent.com/65154/103400652-dbc5c300-4b80-11eb-842b-06f70e5060cf.png">

**Comment by kportertx** [comment]
That warning only applies to when `single-bin` is not set. Please double check your namespace configuration.

**Comment by exherb** [comment]
> That warning only applies to when `single-bin` is not set. Please double check your namespace configuration.

single-bin: false

still a issue I think?

**Comment by bwhisler** [comment]
To clarify the single-bin aspect:

When the namespace has single-bin: false, non-empty bin names must be used in UDFs.
When the namespace has single-bin: true, empty bin names must be used in UDFs.

**Comment by exherb** [comment]
this limitation is very strong. since `as_client.put(key, {"": 1})` will success.

**Comment by exherb** [comment]
when single-bin: true

udf

```lua
local bitlib = require('bit')

function put_or(rec, binname, bit)
  if aerospike:exists(rec) then
    rec[binname] = bitlib.bor(rec[binname], bit)
    return aerospike:update(rec)
  else
    rec[binname] = bit
    return aerospike:create(rec)
  end
end
```
client.udf_put('bitwise.lua')

```python
client.apply(key, 'bitwise', 'put_or', ['', 2])  # return 0
client.get(key)  # return AEROSPIKE_ERR_RECORD_NOT_FOUND
```
